package com.lifly.schedule.desktop.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF0061a6)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd0e4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
val md_theme_light_secondary = Color(0xFF00668a)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFc0e8ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001e2c)
val md_theme_light_tertiary = Color(0xFF784a9a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf4daff)
val md_theme_light_onTertiaryContainer = Color(0xFF2e004f)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfcff)
val md_theme_light_onBackground = Color(0xFF1a1c1e)
val md_theme_light_surface = Color(0xFFfdfcff)
val md_theme_light_onSurface = Color(0xFF1a1c1e)
val md_theme_light_surfaceVariant = Color(0xFFdfe3ec)
val md_theme_light_onSurfaceVariant = Color(0xFF42474e)
val md_theme_light_outline = Color(0xFF72777f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f4)
val md_theme_light_inverseSurface = Color(0xFF2f3033)
val md_theme_light_inversePrimary = Color(0xFF9ccaff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9ccaff)
val md_theme_dark_onPrimary = Color(0xFF00325a)
val md_theme_dark_primaryContainer = Color(0xFF00497f)
val md_theme_dark_onPrimaryContainer = Color(0xFFd0e4ff)
val md_theme_dark_secondary = Color(0xFF72d1ff)
val md_theme_dark_onSecondary = Color(0xFF003549)
val md_theme_dark_secondaryContainer = Color(0xFF004c68)
val md_theme_dark_onSecondaryContainer = Color(0xFFc0e8ff)
val md_theme_dark_tertiary = Color(0xFFe3b5ff)
val md_theme_dark_onTertiary = Color(0xFF471968)
val md_theme_dark_tertiaryContainer = Color(0xFF5f3281)
val md_theme_dark_onTertiaryContainer = Color(0xFFf4daff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1e)
val md_theme_dark_onBackground = Color(0xFFe2e2e6)
val md_theme_dark_surface = Color(0xFF1a1c1e)
val md_theme_dark_onSurface = Color(0xFFe2e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF42474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c7cf)
val md_theme_dark_outline = Color(0xFF8c9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e6)
val md_theme_dark_inversePrimary = Color(0xFF0061a6)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF6750A4)
val error = Color(0xFFba1b1b)